/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "apiKey": string;
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MySearch {
        "searchText": string;
    }
    interface SeachWorlds {
        "searchText": string;
    }
}
export interface MySearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMySearchElement;
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMySearchElement extends Components.MySearch, HTMLStencilElement {
    }
    var HTMLMySearchElement: {
        prototype: HTMLMySearchElement;
        new (): HTMLMySearchElement;
    };
    interface HTMLSeachWorldsElement extends Components.SeachWorlds, HTMLStencilElement {
    }
    var HTMLSeachWorldsElement: {
        prototype: HTMLSeachWorldsElement;
        new (): HTMLSeachWorldsElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
        "my-search": HTMLMySearchElement;
        "seach-worlds": HTMLSeachWorldsElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "apiKey"?: string;
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MySearch {
        "onSearchNameSelected"?: (event: MySearchCustomEvent<string>) => void;
        "searchText"?: string;
    }
    interface SeachWorlds {
        "searchText"?: string;
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-component": MyComponent;
        "my-search": MySearch;
        "seach-worlds": SeachWorlds;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-search": LocalJSX.MySearch & JSXBase.HTMLAttributes<HTMLMySearchElement>;
            "seach-worlds": LocalJSX.SeachWorlds & JSXBase.HTMLAttributes<HTMLSeachWorldsElement>;
        }
    }
}
